
    internal class Example
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Введите a --> ");
            int a = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Введите b --> ");
            int b = Convert.ToInt32(Console.ReadLine());
            int d = a;
            int c = b;
            int g = 0;
            while ((d != 0) && (c != 0))
            {
                d /= 10;
                c /= 10;
                g++;
            }
            int[] mas = new int[g];
            int[] mas1 = new int[g];
            for (int j = 0; j < mas.Length; j++)
            {
                while (a != 0)
                {
                    mas[j] = a % 10;
                    a /= 10;
                }
            }
            for (int l = 0; l < mas1.Length; l++)
            {
                while (b != 0)
                {
                    mas[l] = b % 10;
                    b /= 10;
                }
            }
            for (int j = 0; j < mas.Length; j++)
            {
                for (int l = 0; l < mas1.Length; l++)
                {
                    if (j == l)
                    {
                        int index = l;

                        for (int i = index; i < mas1.Length - 1; i++)
                        {
                            mas1[i] = mas1[i + 1];
                        }
                        Array.Resize(ref mas1, mas1.Length - 1);

                        Console.WriteLine(String.Join(", ", mas1));



                    }
                }

            }
               

        }   
    }
    
}
